
/*
 * PORT_privet.h
 *
 * Created: 10/28/2023 2:51:55 AM
 *  Author: Zeyad
 */ 



#ifndef PORT_PRIVET_H_
#define PORT_PRIVET_H_

#define CONC(b7,b6,b5,b4,b3,b2,b1,b0)				CONC_HELPER(b7,b6,b5,b4,b3,b2,b1,b0)
#define CONC_HELPER(b7,b6,b5,b4,b3,b2,b1,b0)		0b##b7##b6##b5##b4##b3##b2##b1##b0


#define PORTA_DIR								CONC(PORTA_PIN0_DIR,PORTA_PIN1_DIR,PORTA_PIN2_DIR,PORTA_PIN3_DIR,PORTA_PIN4_DIR,PORTA_PIN5_DIR,PORTA_PIN6_DIR,PORTA_PIN7_DIR)
#define PORTB_DIR								CONC(PORTB_PIN0_DIR,PORTB_PIN1_DIR,PORTB_PIN2_DIR,PORTB_PIN3_DIR,PORTB_PIN4_DIR,PORTB_PIN5_DIR,PORTB_PIN6_DIR,PORTB_PIN7_DIR)
#define PORTC_DIR								CONC(PORTC_PIN0_DIR,PORTC_PIN1_DIR,PORTC_PIN2_DIR,PORTC_PIN3_DIR,PORTC_PIN4_DIR,PORTC_PIN5_DIR,PORTC_PIN6_DIR,PORTC_PIN7_DIR)
#define PORTD_DIR								CONC(PORTD_PIN0_DIR,PORTD_PIN1_DIR,PORTD_PIN2_DIR,PORTD_PIN3_DIR,PORTD_PIN4_DIR,PORTD_PIN5_DIR,PORTD_PIN6_DIR,PORTD_PIN7_DIR)

#define PORTA_INITAL_VALUE						CONC(PORTA_PIN0_INITAL_VALUE,PORTA_PIN1_INITAL_VALUE,PORTA_PIN2_INITAL_VALUE,PORTA_PIN3_INITAL_VALUE,PORTA_PIN4_INITAL_VALUE,PORTA_PIN5_INITAL_VALUE,PORTA_PIN6_INITAL_VALUE,PORTA_PIN7_INITAL_VALUE)
#define PORTB_INITAL_VALUE						CONC(PORTB_PIN0_INITAL_VALUE,PORTB_PIN1_INITAL_VALUE,PORTB_PIN2_INITAL_VALUE,PORTB_PIN3_INITAL_VALUE,PORTB_PIN4_INITAL_VALUE,PORTB_PIN5_INITAL_VALUE,PORTB_PIN6_INITAL_VALUE,PORTB_PIN7_INITAL_VALUE)
#define PORTC_INITAL_VALUE						CONC(PORTC_PIN0_INITAL_VALUE,PORTC_PIN1_INITAL_VALUE,PORTC_PIN2_INITAL_VALUE,PORTC_PIN3_INITAL_VALUE,PORTC_PIN4_INITAL_VALUE,PORTC_PIN5_INITAL_VALUE,PORTC_PIN6_INITAL_VALUE,PORTC_PIN7_INITAL_VALUE)
#define PORTD_INITAL_VALUE						CONC(PORTD_PIN0_INITAL_VALUE,PORTD_PIN1_INITAL_VALUE,PORTD_PIN2_INITAL_VALUE,PORTD_PIN3_INITAL_VALUE,PORTD_PIN4_INITAL_VALUE,PORTD_PIN5_INITAL_VALUE,PORTD_PIN6_INITAL_VALUE,PORTD_PIN7_INITAL_VALUE)


#endif
